def show_title():
    print("🌌 Exploring God's Magnificent Universe")
    print("✨ 'The heavens declare the glory of God' - Psalm 19:1")
    print()


# Mission variables - accessible from main.py
mission1 = "perseverance rover - mars exploration"
mission1_formatted = mission1.title()  # "Perseverance Rover - Mars Exploration"
mission2 = "james webb space telescope - deep space observation"
mission2_formatted = mission2.title()  # "James Webb Space Telescope - Deep Space Observation"
mission3 = "voyager 1 - interstellar space"
mission3_formatted = mission3.title()  # "Voyager 1 - Interstellar Space"
mission4 = "hubble space telescope - earth orbit observation"
mission4_formatted = mission4.title()  # "Hubble Space Telescope - Earth Orbit Observation"
mission5 = "curiosity rover - mars surface analysis"
mission5_formatted = mission5.title()  # "Curiosity Rover - Mars Surface Analysis"
mission6 = "spitzer space telescope - infrared astronomy"
mission6_formatted = mission6.title()  # "Spitzer Space Telescope - Infrared Astronomy"
mission7 = "cassini-huygens - saturn exploration"
mission7_formatted = mission7.title()  # "Cassini-Huygens - Saturn Exploration"
mission8 = "new horizons - pluto and beyond"
mission8_formatted = mission8.title()  # "New Horizons - Pluto and Beyond"
mission9 = "galileo - jupiter exploration"
mission9_formatted = mission9.title()  # "Galileo - Jupiter Exploration"
mission10 = "kepler space telescope - exoplanet discovery"
mission10_formatted = mission10.title()  # "Kepler Space Telescope - Exoplanet Discovery"
mission11 = "chandra x-ray observatory - x-ray astronomy"
mission11_formatted = mission11.title()  # "Chandra X-Ray Observatory - X-Ray Astronomy"
mission12 = "juno - jupiter polar orbiter"
mission12_formatted = mission12.title()  # "Juno - Jupiter Polar Orbiter"
mission13 = "tess - exoplanet survey satellite"
mission13_formatted = mission13.title()  # "TESS - Exoplanet Survey Satellite"
mission14 = "osiris-rex - asteroid sample return"
mission14_formatted = mission14.title()  # "OSIRIS-REx - Asteroid Sample Return"
mission15 = "dawn - asteroid belt exploration"
mission15_formatted = mission15.title()  # "Dawn - Asteroid Belt Exploration
mission16 = "spacex starship - interplanetary travel vehicle"
mission16_formatted = mission16.title()  # "SpaceX Starship - Interplanetary Travel Vehicle"
mission17 = "blue origin new shepard - suborbital spaceflight"
mission17_formatted = mission17.title()  # "Blue Origin New Shepard - Suborbital Spaceflight"
mission18 = "ariane 5 - heavy lift launch vehicle"
mission18_formatted = mission18.title()  # "Ariane 5 - Heavy Lift Launch Vehicle"
mission19 = "soyuz - human spaceflight"
mission19_formatted = mission19.title()  # "Soyuz - Human Spaceflight"
mission20 = "falcon 9 - reusable rocket"
mission20_formatted = mission20.title()  # "Falcon 9 - Reusable Rocket"
mission21 = "atlas v - versatile launch vehicle"
mission21_formatted = mission21.title()  # "Atlas V - Versatile Launch Vehicle"
mission22 = "delta iv heavy - heavy lift launch vehicle"
mission22_formatted = mission22.title()  # "Delta IV Heavy - Heavy Lift Launch Vehicle"
mission23 = "sls - deep space exploration"
mission23_formatted = mission23.title()  # "SLS - Deep Space Exploration"
mission24 = "crew dragon - human spaceflight"
mission25_formatted = mission24.title()  # "Crew Dragon - Human Spaceflight"
mission25 = "starlink - satellite internet constellation"
