def show_title():
    print("🌌 Exploring God's Magnificent Universe")
    print("✨ 'The heavens declare the glory of God' - Psalm 19:1")
    print()


# Mission variables - accessible from main.py
mission1 = "perseverance rover - mars exploration"
mission1_formatted = mission1.capitalize()  # "Perseverance rover - mars exploration"
mission2 = "james webb space telescope - deep space observation"
mission2_formatted = mission2.capitalize()  # "James webb space telescope - deep space observation"
mission3 = "voyager 1 - interstellar space"
mission3_formatted = mission3.capitalize()  # "Voyager 1 - interstellar space"
mission4 = "hubble space telescope - earth orbit observation"
mission4_formatted = mission4.capitalize()  # "Hubble space telescope - earth orbit observation"
mission5 = "curiosity rover - mars surface analysis"
mission5_formatted = mission5.capitalize()  # "Curiosity rover - mars surface analysis"
mission6 = "spitzer space telescope - infrared astronomy"
mission6_formatted = mission6.capitalize()  # "Spitzer space telescope - infrared astronomy"
mission7 = "cassini-huygens - saturn exploration"
mission7_formatted = mission7.capitalize()  # "Cassini-huygens - saturn exploration"
mission8 = "new horizons - pluto and beyond"
mission8_formatted = mission8.capitalize()  # "New horizons - pluto and beyond"
mission9 = "galileo - jupiter exploration"
mission9_formatted = mission9.capitalize()  # "Galileo - jupiter exploration"
mission10 = "kepler space telescope - exoplanet discovery"
mission10_formatted = mission10.capitalize()  # "Kepler space telescope - exoplanet discovery"
mission11 = "chandra x-ray observatory - x-ray astronomy"
mission11_formatted = mission11.capitalize()  # "Chandra x-ray observatory - x-ray astronomy"
mission12 = "juno - jupiter polar orbiter"
mission12_formatted = mission12.capitalize()  # "Juno - jupiter polar orbiter"
mission13 = "tess - exoplanet survey satellite"
mission13_formatted = mission13.capitalize()  # "Tess - exoplanet survey satellite"
mission14 = "osiris-rex - asteroid sample return"
mission14_formatted = mission14.capitalize()  # "Osiris-rex - asteroid sample return"
mission15 = "dawn - asteroid belt exploration"
mission15_formatted = mission15.capitalize()  # "Dawn - asteroid belt exploration"
mission16 = "spacex starship - interplanetary travel vehicle"
mission16_formatted = mission16.capitalize()  # "Spacex starship - interplanetary travel vehicle"
mission17 = "blue origin new shepard - suborbital spaceflight"
mission17_formatted = mission17.capitalize()  # "Blue origin new shepard - suborbital spaceflight"
mission18 = "ariane 5 - heavy lift launch vehicle"
mission18_formatted = mission18.capitalize()  # "Ariane 5 - heavy lift launch vehicle"
mission19 = "soyuz - human spaceflight"
mission19_formatted = mission19.capitalize()  # "Soyuz - human spaceflight"
mission20 = "falcon 9 - reusable rocket"
mission20_formatted = mission20.capitalize()  # "Falcon 9 - reusable rocket"
mission21 = "atlas v - versatile launch vehicle"
mission21_formatted = mission21.capitalize()  # "Atlas v - versatile launch vehicle"
mission22 = "delta iv heavy - heavy lift launch vehicle"
mission22_formatted = mission22.capitalize()  # "Delta iv heavy - heavy lift launch vehicle"
mission23 = "sls - deep space exploration"
mission23_formatted = mission23.capitalize()  # "Sls - deep space exploration"
mission24 = "crew dragon - human spaceflight"
mission24_formatted = mission24.capitalize()  # "Crew dragon - human spaceflight"
mission25 = "starlink - satellite internet constellation"
mission25_formatted = mission25.capitalize()  # "Starlink - satellite internet constellation"
